version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - 5000:5000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    container_name: worker
    entrypoint: ["celery", "--app", "tasks", "worker", "--loglevel=info", "--concurrency=2"]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis

  redis:
    container_name: redis
    image: redis:latest